name: Refresh Token, Compress, and Upload Images & Video Thumbnails Incrementally

on:
  push:
    branches:
      - main

jobs:
  compress-media:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install Python, ImageMagick, ffmpeg, and jq
      - name: Install Python, ImageMagick, ffmpeg, and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip imagemagick jq ffmpeg

      # Step 4: Refresh Dropbox Access Token
      - name: Refresh Dropbox Access Token
        id: refresh_token
        env:
          CLIENT_ID: ${{ secrets.DROPBOX_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DROPBOX_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
        run: |
          response=$(curl -X POST https://api.dropboxapi.com/oauth2/token \
            --data "grant_type=refresh_token&refresh_token=$REFRESH_TOKEN&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET" \
            -H "Content-Type: application/x-www-form-urlencoded")
          
          ACCESS_TOKEN=$(echo $response | jq -r '.access_token')
          echo "::set-output name=access_token::$ACCESS_TOKEN"

      # Updated Step 5: Search and process images incrementally
      - name: Search and process images incrementally
        env:
          ACCESS_TOKEN: ${{ steps.refresh_token.outputs.access_token }}
        run: |
          mkdir -p downloaded_images compressed_images
          echo "Searching for all image files in Dropbox..."

          # Function to process a single image
          process_image() {
            local path="$1"
            local filename=$(basename "$path")
            filename=$(echo "$filename" | tr ' ' '_')  # Replace spaces with underscores
            
            if [ ! -f "compressed_images/$filename" ]; then
              echo "Checking metadata for $path..."
              metadata_response=$(curl -s -X POST https://api.dropboxapi.com/2/files/get_metadata \
                --header "Authorization: Bearer $ACCESS_TOKEN" \
                --header "Content-Type: application/json" \
                --data "{\"path\": \"$path\"}")
              
              # Extract file size using jq
              file_size=$(echo "$metadata_response" | jq -r '.size // empty')
              
              if [ -z "$file_size" ]; then
                echo "Failed to get file size for $path, skipping"
                return
              fi

              if [ "$file_size" -gt 100000000 ]; then  # 100MB in bytes
                echo "File $filename is too large ($file_size bytes), skipping"
                return
              fi

              echo "Generating temporary link for $path..."
              temp_link_response=$(curl -X POST https://api.dropboxapi.com/2/files/get_temporary_link \
                --header "Authorization: Bearer $ACCESS_TOKEN" \
                --header "Content-Type: application/json" \
                --data "{\"path\": \"$path\"}")
              temp_link=$(echo "$temp_link_response" | jq -r '.link')

              if [ "$temp_link" != "null" ]; then
                echo "Downloading $filename from $temp_link"
                curl -L "$temp_link" -o "downloaded_images/$filename"

                # Compress the image
                echo "Compressing $filename..."
                mogrify -path compressed_images -resize 50% "downloaded_images/$filename" || echo "Error compressing $filename"

                # Commit and push the compressed image
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git config --global user.name "github-actions[bot]"
                git add compressed_images/$filename || echo "No matching files"
                git commit -m "Add compressed image: $filename" || echo "No changes to commit"
                git push https://x-access-token:${{ secrets.ACTIONS_DEPLOY_TOKEN }}@github.com/kevinveragit/MacLellan-Frontend.git

                # Remove the original downloaded image to save space
                rm "downloaded_images/$filename"
              else
                echo "Failed to get temporary link for $path"
              fi
            else
              echo "$filename is already compressed, skipping."
            fi
          }

          # Search for files with image extensions recursively
          cursor=""
          has_more=true

          while $has_more; do
            response=$(curl -X POST https://api.dropboxapi.com/2/files/search_v2/continue \
              --header "Authorization: Bearer $ACCESS_TOKEN" \
              --header "Content-Type: application/json" \
              --data "{
                \"cursor\": \"$cursor\"
              }")

            echo "$response" | jq -r '.matches[] | select(.metadata.metadata[".tag"] == "file") | .metadata.metadata.path_lower' \
            | while read -r path; do
                if [[ $path =~ \.(jpg|jpeg|png|gif|heic|tiff|bmp)$ ]]; then
                  process_image "$path"
                fi
            done

            has_more=$(echo "$response" | jq -r '.has_more')
            cursor=$(echo "$response" | jq -r '.cursor')

            if [ "$has_more" = "false" ]; then
              break
            fi
          done

      # Updated Step 6: Search and process video thumbnails incrementally using get_thumbnail_v2
      - name: Search and process video thumbnails incrementally
        env:
          ACCESS_TOKEN: ${{ steps.refresh_token.outputs.access_token }}
        run: |
          mkdir -p downloaded_video_thumbnails compressed_video_thumbnails
          echo "Searching for all video files in Dropbox..."

          # Search for files with video extensions recursively
          response=$(curl -X POST https://api.dropboxapi.com/2/files/search_v2 \
            --header "Authorization: Bearer $ACCESS_TOKEN" \
            --header "Content-Type: application/json" \
            --data '{
              "query": ".mp4 OR .avi OR .mkv OR .mov",
              "options": {
                "filename_only": true,
                "file_status": "active",
                "max_results": 1000
              }
            }')

          # Process each video one by one to get thumbnails
          echo "$response" | jq -r '.matches[] | select(.metadata.metadata[".tag"] == "file") | .metadata.metadata.path_lower' \
          | while read -r path; do
              video_filename=$(basename "$path")
              thumbnail_filename="${video_filename%.*}-video.jpg"  # Use the video name with -video suffix
              thumbnail_filename=$(echo "$thumbnail_filename" | tr ' ' '_')  # Replace spaces with underscores

              if [ ! -f "compressed_video_thumbnails/$thumbnail_filename" ]; then
                echo "Generating thumbnail for $path..."
                
                # Use get_thumbnail_v2 to get a high-quality thumbnail
                thumbnail_response=$(curl -X POST https://content.dropboxapi.com/2/files/get_thumbnail_v2 \
                  --header "Authorization: Bearer $ACCESS_TOKEN" \
                  --header "Dropbox-API-Arg: {\"resource\": {\"path\": \"$path\"}, \"format\": \"jpeg\", \"size\": \"w1024h768\"}" \
                  --output "downloaded_video_thumbnails/$thumbnail_filename")

                if [ -f "downloaded_video_thumbnails/$thumbnail_filename" ]; then
                  # Compress the thumbnail
                  echo "Compressing thumbnail $thumbnail_filename..."
                  mkdir -p compressed_video_thumbnails
                  mogrify -path compressed_video_thumbnails -resize 50% "downloaded_video_thumbnails/$thumbnail_filename" || echo "Error compressing thumbnail $thumbnail_filename"

                  # Commit and push the compressed thumbnail
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"
                  git add compressed_video_thumbnails/$thumbnail_filename || echo "No matching files"
                  git commit -m "Add compressed video thumbnail: $thumbnail_filename" || echo "No changes to commit"
                  git push https://x-access-token:${{ secrets.ACTIONS_DEPLOY_TOKEN }}@github.com/kevinveragit/MacLellan-Frontend.git

                  # Remove the original downloaded thumbnail to save space
                  rm "downloaded_video_thumbnails/$thumbnail_filename"
                else
                  echo "Failed to get thumbnail for $path"
                fi
              else
                echo "$thumbnail_filename is already compressed, skipping."
              fi
          done

      # Debug Step: Check if images and thumbnails were downloaded and compressed
      - name: List downloaded and compressed media
        run: |
          echo "Downloaded Images:"
          ls -l downloaded_images
          echo "Compressed Images:"
          ls -l compressed_images
          echo "Downloaded Video Thumbnails:"
          ls -l downloaded_video_thumbnails
          echo "Compressed Video Thumbnails:"
          ls -l compressed_video_thumbnails
