name: Refresh Token, Compress, and Upload Images

on:
  push:
    branches:
      - main

jobs:
  compress-images:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install Python, ImageMagick, and jq
      - name: Install Python and ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip imagemagick jq

      # Step 4: Refresh Dropbox Access Token
      - name: Refresh Dropbox Access Token
        id: refresh_token
        env:
          CLIENT_ID: ${{ secrets.DROPBOX_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DROPBOX_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
        run: |
          response=$(curl -X POST https://api.dropboxapi.com/oauth2/token \
            --data "grant_type=refresh_token&refresh_token=$REFRESH_TOKEN&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET" \
            -H "Content-Type: application/x-www-form-urlencoded")
          
          ACCESS_TOKEN=$(echo $response | jq -r '.access_token')
          echo "::set-output name=access_token::$ACCESS_TOKEN"

      # Step 5: Search for every image in Dropbox using Search v2 API
      - name: Search and download all images from Dropbox
        env:
          ACCESS_TOKEN: ${{ steps.refresh_token.outputs.access_token }}
        run: |
          mkdir -p downloaded_images
          echo "Searching for all image files in Dropbox..."

          # Search for files with specific extensions recursively
          response=$(curl -X POST https://api.dropboxapi.com/2/files/search_v2 \
            --header "Authorization: Bearer $ACCESS_TOKEN" \
            --header "Content-Type: application/json" \
            --data '{
              "query": ".jpg OR .jpeg OR .png OR .gif OR .heic",
              "options": {
                "filename_only": true,
                "file_status": "active",
                "max_results": 1000
              }
            }')

          echo "Full Dropbox API Search Response: $response"

          # Filter search results to get only image files and use get_temporary_link to download
          echo "$response" | jq -r '.matches[] | select(.metadata.metadata[".tag"] == "file") | .metadata.metadata.path_lower' \
          | while read -r path; do
              echo "Generating temporary link for $path..."
              temp_link_response=$(curl -X POST https://api.dropboxapi.com/2/files/get_temporary_link \
                --header "Authorization: Bearer $ACCESS_TOKEN" \
                --header "Content-Type: application/json" \
                --data "{\"path\": \"$path\"}")
              echo "Temporary link response: $temp_link_response"
              
              temp_link=$(echo "$temp_link_response" | jq -r '.link')

              # Download the image using the temporary link
              if [ "$temp_link" != "null" ]; then
                filename=$(basename "$path")
                echo "Downloading $filename from $temp_link"
                curl -L "$temp_link" -o "downloaded_images/$filename"
              else
                echo "Failed to get temporary link for $path"
              fi
          done
      
      # Debug Step: Check if images were downloaded
      - name: List downloaded images
        run: ls -l downloaded_images

      # Step 6: Compress images using ImageMagick
      - name: Compress images
        run: |
          mkdir -p compressed_images
          for img in downloaded_images/*; do
            if file "$img" | grep -qE 'image|bitmap'; then
              echo "Compressing $img..."
              mogrify -path compressed_images -resize 50% "$img" || echo "Error processing $img, skipping..."
            else
              echo "Skipping non-image file $img"
            fi
          done

      # Debug Step: Check if images were compressed
      - name: List compressed images
        run: ls -l compressed_images

      # Step 7: Commit and push compressed images using PAT
      - name: Commit and push compressed images
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add compressed_images/
          git commit -m "Add compressed images" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.ACTIONS_DEPLOY_TOKEN }}@github.com/kevinveragit/MacLellan-Frontend.git
