name: Recursive Dropbox Media Processing

on:
  push:
    branches:
      - main

jobs:
  process-media:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip imagemagick jq ffmpeg

      - name: Refresh Dropbox Access Token
        id: refresh_token
        env:
          CLIENT_ID: ${{ secrets.DROPBOX_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DROPBOX_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
        run: |
          response=$(curl -X POST https://api.dropboxapi.com/oauth2/token \
            --data "grant_type=refresh_token&refresh_token=$REFRESH_TOKEN&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET" \
            -H "Content-Type: application/x-www-form-urlencoded")
          ACCESS_TOKEN=$(echo $response | jq -r '.access_token')
          echo "::set-output name=access_token::$ACCESS_TOKEN"

      - name: Process Dropbox folders recursively
        env:
          ACCESS_TOKEN: ${{ steps.refresh_token.outputs.access_token }}
        run: |
          process_folder() {
            local folder_path="$1"
            echo "Processing folder: $folder_path"
            
            # List folder contents
            response=$(curl -X POST https://api.dropboxapi.com/2/files/list_folder \
              --header "Authorization: Bearer $ACCESS_TOKEN" \
              --header "Content-Type: application/json" \
              --data "{\"path\": \"$folder_path\", \"recursive\": false}")
            
            # Process each entry in the folder
            echo "$response" | jq -c '.entries[]' | while read -r entry; do
              path=$(echo "$entry" | jq -r '.path_display')
              tag=$(echo "$entry" | jq -r '.".tag"')
              
              if [ "$tag" = "folder" ]; then
                # Recursively process subfolders
                process_folder "$path"
              elif [ "$tag" = "file" ]; then
                # Process file based on its extension
                extension="${path##*.}"
                filename=$(basename "$path")
                filename_without_ext="${filename%.*}"
                
                case "$extension" in
                  jpg|jpeg|png|gif|heic)
                    process_image "$path" "$filename"
                    ;;
                  mp4|avi|mkv|mov)
                    process_video_thumbnail "$path" "$filename_without_ext"
                    ;;
                  *)
                    echo "Skipping unsupported file: $path"
                    ;;
                esac
              fi
            done
          }

          process_image() {
            local path="$1"
            local filename="$2"
            
            if [ ! -f "compressed_images/$filename" ]; then
              echo "Processing image: $path"
              encoded_path=$(printf '%s' "$path" | jq -sRr @uri)
              temp_link_response=$(curl -X POST https://api.dropboxapi.com/2/files/get_temporary_link \
                --header "Authorization: Bearer $ACCESS_TOKEN" \
                --header "Content-Type: application/json" \
                --data "{\"path\": \"$encoded_path\"}")
              
              temp_link=$(echo "$temp_link_response" | jq -r '.link')
              if [ "$temp_link" != "null" ] && [ -n "$temp_link" ]; then
                curl -L "$temp_link" -o "temp_$filename"
                mogrify -path compressed_images -resize 50% "temp_$filename"
                rm "temp_$filename"
                git add compressed_images/$filename
                git commit -m "Add compressed image: $filename" || echo "No changes to commit for $filename"
              else
                echo "Failed to get temporary link for $path"
              fi
            else
              echo "$filename is already compressed, skipping."
            fi
          }

          process_video_thumbnail() {
            local path="$1"
            local filename_without_ext="$2"
            
            if [ ! -f "compressed_video_thumbnails/${filename_without_ext}.jpg" ]; then
              echo "Processing video thumbnail: $path"
              encoded_path=$(printf '%s' "$path" | jq -sRr @uri)
              thumbnail_response=$(curl -X POST https://content.dropboxapi.com/2/files/get_thumbnail_v2 \
                --header "Authorization: Bearer $ACCESS_TOKEN" \
                --header "Dropbox-API-Arg: {\"resource\": {\"path\": \"$encoded_path\"}, \"format\": \"jpeg\", \"size\": \"w1024h768\", \"mode\": \"bestfit\"}" \
                --output "temp_${filename_without_ext}.jpg")
              
              if [ -f "temp_${filename_without_ext}.jpg" ]; then
                mogrify -path compressed_video_thumbnails -resize 50% "temp_${filename_without_ext}.jpg"
                rm "temp_${filename_without_ext}.jpg"
                git add compressed_video_thumbnails/${filename_without_ext}.jpg
                git commit -m "Add compressed video thumbnail: ${filename_without_ext}.jpg" || echo "No changes to commit for ${filename_without_ext}.jpg"
              else
                echo "Failed to download thumbnail for $path"
              fi
            else
              echo "${filename_without_ext}.jpg thumbnail already exists, skipping."
            fi
          }

          # Ensure directories exist
          mkdir -p compressed_images compressed_video_thumbnails

          # Start processing from the root folder
          process_folder ""

          # Push all changes
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git push https://x-access-token:${{ secrets.ACTIONS_DEPLOY_TOKEN }}@github.com/kevinveragit/MacLellan-Frontend.git

      - name: List processed media
        run: |
          echo "Compressed Images:"
          ls -l compressed_images
          echo "Compressed Video Thumbnails:"
          ls -l compressed_video_thumbnails