name: Process Uploaded Images

on:
  push:
    branches:
      - main
    paths:
      - 'images/**'

jobs:
  process-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23
        with:
          files: |
            images/**/*.jpg
            images/**/*.jpeg
            images/**/*.png
            images/**/*.gif
            images/**/*.heic

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow

      - name: Process new images
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          import os
          from PIL import Image
          
          def process_image(file_path):
              try:
                  with Image.open(file_path) as img:
                      # Resize if larger than 2000x2000
                      if img.width > 2000 or img.height > 2000:
                          img.thumbnail((2000, 2000))
                      
                      # Convert to RGB if CMYK
                      if img.mode == 'CMYK':
                          img = img.convert('RGB')
                      
                      # Save with optimized settings
                      img.save(file_path, optimize=True, quality=85)
                  print(f"Processed: {file_path}")
              except Exception as e:
                  print(f"Error processing {file_path}: {str(e)}")

          changed_files = "${{ steps.changed-files.outputs.all_changed_files }}".split()
          for file in changed_files:
              if file.lower().endswith(('.jpg', '.jpeg', '.png', '.gif', '.heic')):
                  process_image(file)
        shell: python

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add images
          git diff --quiet && git diff --staged --quiet || (git commit -m "Process uploaded images" && git push)